### ISSUE TITLE
Error in log on 10.8.0.0

### ISSUE THREAD

**Issue by kellcomnet2** [jellyfin/jellyfin-plugin-musicbrainz#18]
[2022-05-02 13:38:17.913 +00:00] [ERR] [116] MediaBrowser.Providers.Music.AlbumMetadataService: Error in "MusicBrainz"
System.InvalidOperationException: Set XmlReaderSettings.Async to true if you want to use Async Methods.
   at System.Xml.XmlTextReaderImpl.CheckAsyncCall()
   at System.Xml.XmlTextReaderImpl.ReadAsync()
   at System.Xml.XmlReader.MoveToContentAsync()
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetReleaseGroupFromReleaseId(String releaseEntryId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetReleaseGroupFromReleaseId(String releaseEntryId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)

**Comment by crobibero** [comment]
This plugin is not yet used. Please repopen this issue (with more logs) in the server repo.
